import { Pagination } from "../../common/type";
import { Kir } from "./kir";

export type KirCreateParam = {
  certificateNumber?: string;
  director?: string;
  directorLevel?: string;
  directorNip?: string;
  directorStamp?: string;
  directorSignature?: string;
  owner?: string;
  address?: string;
  cardNumber?: string;
  rfid?: string;
  registrationDate?: string;
  registrationNumber?: string;
  chasisNumber?: string;
  engineNumber?: string;
  inspectionNumber?: string;
  frontPic?: string;
  backPic?: string;
  rightPic?: string;
  leftPic?: string;
  vehicleType?: string;
  vehicleBrand?: string;
  yearManufacture?: string;
  fuel?: string;
  engineCapacity?: string;
  enginePower?: string;
  tyreSize?: string;
  axleConfiguration?: string;
  curbWeight?: string;
  length?: string;
  width?: string;
  height?: string;
  front?: string;
  back?: string;
  sumbu1?: string;
  sumbu2?: string;
  sumbu3?: string;
  dimension?: string;
  jbbJbkb?: string;
  jbiJbki?: string;
  payload?: string;
  classPermit?: string;
  mst?: string;
  brake1?: string;
  brake2?: string;
  brake3?: string;
  brake4?: string;
  brake5?: string;
  headLamp1?: string;
  headLamp2?: string;
  headLamp3?: string;
  headLamp4?: string;
  coEmision?: string;
  hcEmision?: string;
  smokeDensity?: string;
  inspectionResult?: string;
  inspector?: string;
  inspectorLevel?: string;
  inspectorNumber?: string;
  inspectorStamp?: string;
  inspectorSignature?: string;
  inspectionUnit?: string;
  region?: string;
  origin?: string;
  agency?: string;
  agencyLevel?: string;
  agencyNumber?: string;
  agencyStamp?: string;
  agencySignature?: string;
  qr?: string;
};

export type KirUpdateParam = {
  id: number;
  certificateNumber?: string;
  director?: string;
  directorLevel?: string;
  directorNip?: string;
  directorStamp?: string;
  directorSignature?: string;
  owner?: string;
  address?: string;
  cardNumber?: string;
  rfid?: string;
  registrationDate?: string;
  registrationNumber?: string;
  chasisNumber?: string;
  engineNumber?: string;
  inspectionNumber?: string;
  frontPic?: string;
  backPic?: string;
  rightPic?: string;
  leftPic?: string;
  vehicleType?: string;
  vehicleBrand?: string;
  yearManufacture?: string;
  fuel?: string;
  engineCapacity?: string;
  enginePower?: string;
  tyreSize?: string;
  axleConfiguration?: string;
  curbWeight?: string;
  length?: string;
  width?: string;
  height?: string;
  front?: string;
  back?: string;
  sumbu1?: string;
  sumbu2?: string;
  sumbu3?: string;
  dimension?: string;
  jbbJbkb?: string;
  jbiJbki?: string;
  payload?: string;
  classPermit?: string;
  mst?: string;
  brake1?: string;
  brake2?: string;
  brake3?: string;
  brake4?: string;
  brake5?: string;
  headLamp1?: string;
  headLamp2?: string;
  headLamp3?: string;
  headLamp4?: string;
  coEmision?: string;
  hcEmision?: string;
  smokeDensity?: string;
  inspectionResult?: string;
  inspector?: string;
  inspectorLevel?: string;
  inspectorNumber?: string;
  inspectorStamp?: string;
  inspectorSignature?: string;
  inspectionUnit?: string;
  region?: string;
  origin?: string;
  agency?: string;
  agencyLevel?: string;
  agencyNumber?: string;
  agencyStamp?: string;
  agencySignature?: string;
  qr?: string;
};

export type KirListParam = {
  certificateNumber?: string;
  pagination?: Pagination;
};

export abstract class KirApi {
  abstract create(param: KirCreateParam): Promise<void>;
  abstract read(id: string): Promise<Kir | undefined>;
  abstract update(param: KirUpdateParam): Promise<void>;
  abstract remove(id: string): Promise<void>;
  abstract list(param?: KirListParam): Promise<Kir[]>;
  abstract find(certificateNumber: string): Promise<Kir | undefined>;
}
